spring.application.name=payment-service
server.port=8085

spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.tsbtieescvvbafckwwge
spring.datasource.password=f32W9zyzgfYfbnY3
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.default_schema=public
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=600000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# SePAY / Bank config
sepay.bank.account-number=106875326574
sepay.bank.bank-name=Vietinbank
sepay.bank.qr-base-url=https://qr.sepay.vn/img

# Ordering Service URL (internal Docker network)
ordering.service.url=http://ordering-service:8082
payment.default-tax-rate=10.0
